import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, CheckCircle2, XCircle, Smartphone, AlertTriangle } from 'lucide-react';

// Public self-service payment page. No authentication required.
// Accessed via /pay/:token — token generated by generatePaymentLink function.

export default function PayPage() {
  const { token } = useParams();
  const [link, setLink] = useState(null);
  const [customer, setCustomer] = useState(null);
  const [invoice, setInvoice] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [phone, setPhone] = useState('');
  const [paying, setPaying] = useState(false);
  const [result, setResult] = useState(null);

  useEffect(() => {
    async function loadLink() {
      try {
        const links = await base44.entities.PaymentLink.filter({ token, status: 'active' });
        const pl = links?.[0];
        if (!pl) { setError('Payment link not found or has expired.'); setLoading(false); return; }

        // Check expiry
        if (pl.expires_at && new Date(pl.expires_at) < new Date()) {
          await base44.entities.PaymentLink.update(pl.id, { status: 'expired' });
          setError('This payment link has expired. Please contact NLSWMS for a new link.');
          setLoading(false);
          return;
        }

        setLink(pl);

        // Load customer
        if (pl.customer_id) {
          const customers = await base44.entities.Customer.filter({ id: pl.customer_id });
          const c = customers?.[0];
          setCustomer(c);
          if (c?.phone) setPhone(c.phone);
        }

        // Load invoice if linked
        if (pl.invoice_id) {
          const invoices = await base44.entities.Invoice.filter({ id: pl.invoice_id });
          setInvoice(invoices?.[0] || null);
        }
      } catch (e) {
        setError(e.message || 'Failed to load payment link.');
      } finally {
        setLoading(false);
      }
    }
    if (token) loadLink();
  }, [token]);

  const handlePay = async () => {
    if (!phone.trim()) { setError('Please enter your mobile money number.'); return; }
    setError('');
    setPaying(true);
    try {
      const res = await base44.functions.invoke('initiateYoPayment', {
        customer_id: link.customer_id,
        invoice_id: link.invoice_id || undefined,
        phone: phone.trim(),
        amount_ugx: link.amount_ugx,
        narration: link.description || 'NLSWMS Payment',
        reference: `LINK-${token.slice(0, 8)}-${Date.now()}`,
      });
      const data = res.data || res;

      if (data.provisioned) {
        setResult({ success: true, provisioned: true, message: data.message });
      } else if (data.paid) {
        setResult({ success: true, paid: true, payment_reference: data.payment_reference });
        // Mark link as used
        await base44.entities.PaymentLink.update(link.id, { status: 'used', used_at: new Date().toISOString() });
      } else {
        setResult({ success: false, message: `Payment status: ${data.status || 'unknown'}. Please check your phone for a MoMo prompt and try again.` });
      }
    } catch (e) {
      setError(e.message || 'Payment failed. Please try again.');
    } finally {
      setPaying(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error && !link) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background px-4">
        <Card className="max-w-sm w-full border-destructive/40">
          <CardContent className="pt-8 pb-8 text-center">
            <XCircle className="w-12 h-12 text-destructive mx-auto mb-4" />
            <h2 className="text-lg font-bold font-jakarta mb-2">Link Invalid</h2>
            <p className="text-sm text-muted-foreground">{error}</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (result?.paid) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background px-4">
        <Card className="max-w-sm w-full border-green-200">
          <CardContent className="pt-8 pb-8 text-center">
            <CheckCircle2 className="w-14 h-14 text-green-500 mx-auto mb-4" />
            <h2 className="text-xl font-bold font-jakarta text-green-700 mb-1">Payment Successful!</h2>
            <p className="text-sm text-muted-foreground mb-3">Your payment of <span className="font-semibold text-foreground">{(link.amount_ugx || 0).toLocaleString()} UGX</span> has been received.</p>
            {result.payment_reference && (
              <p className="text-xs font-mono bg-muted rounded-lg px-3 py-2 inline-block">Ref: {result.payment_reference}</p>
            )}
            <p className="text-xs text-muted-foreground mt-4">A receipt has been sent to your phone. Thank you!</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex items-center justify-center px-4 py-8">
      <div className="w-full max-w-sm space-y-4">
        {/* Header */}
        <div className="text-center mb-2">
          <div className="w-12 h-12 rounded-full bg-primary flex items-center justify-center mx-auto mb-3">
            <Smartphone className="w-6 h-6 text-white" />
          </div>
          <h1 className="text-xl font-bold font-jakarta">NLSWMS Payment</h1>
          <p className="text-xs text-muted-foreground mt-1">Secure mobile money payment</p>
        </div>

        {/* Payment Details */}
        <Card className="border-border/60">
          <CardHeader className="pb-2 pt-4">
            <CardTitle className="text-sm font-medium text-muted-foreground">Payment Details</CardTitle>
          </CardHeader>
          <CardContent className="pb-4 space-y-2">
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">Customer</span>
              <span className="text-sm font-semibold">{customer?.full_name || '—'}</span>
            </div>
            {invoice && (
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Invoice</span>
                <span className="text-sm font-mono">{invoice.invoice_number}</span>
              </div>
            )}
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">Description</span>
              <span className="text-sm">{link?.description || 'NLSWMS Payment'}</span>
            </div>
            <div className="flex justify-between items-center pt-2 border-t border-border/60">
              <span className="text-sm font-semibold">Amount</span>
              <span className="text-lg font-bold font-jakarta text-primary">{(link?.amount_ugx || 0).toLocaleString()} <span className="text-xs font-normal text-muted-foreground">UGX</span></span>
            </div>
            {link?.expires_at && (
              <p className="text-xs text-muted-foreground text-right">
                Expires: {new Date(link.expires_at).toLocaleDateString('en-UG', { dateStyle: 'medium' })}
              </p>
            )}
          </CardContent>
        </Card>

        {/* Payment Form */}
        {result?.provisioned ? (
          <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-xl text-sm text-yellow-800">
            <AlertTriangle className="w-4 h-4 inline mr-2" />
            {result.message}
          </div>
        ) : (
          <Card className="border-border/60">
            <CardContent className="pt-4 pb-4 space-y-3">
              <div>
                <label className="text-xs text-muted-foreground block mb-1.5">Mobile Money Number</label>
                <Input
                  value={phone}
                  onChange={e => setPhone(e.target.value)}
                  placeholder="e.g. 0771234567"
                  className="text-sm"
                  type="tel"
                  disabled={paying}
                />
                <p className="text-[10px] text-muted-foreground mt-1">Enter the MTN MoMo or Airtel Money number to charge.</p>
              </div>
              {error && (
                <p className="text-xs text-destructive flex items-center gap-1">
                  <AlertTriangle className="w-3 h-3" /> {error}
                </p>
              )}
              <Button onClick={handlePay} disabled={paying || !phone.trim()} className="w-full gap-2">
                {paying ? <Loader2 className="w-4 h-4 animate-spin" /> : <Smartphone className="w-4 h-4" />}
                {paying ? 'Processing...' : `Pay ${(link?.amount_ugx || 0).toLocaleString()} UGX`}
              </Button>
              <p className="text-[10px] text-center text-muted-foreground">You will receive a MoMo prompt on your phone to confirm payment.</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
