import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    const body = await req.json().catch(() => ({}));
    const { event, data } = body;

    // Only act on container updates
    if (event?.type !== 'update') {
      return Response.json({ skipped: true });
    }

    const container = data;
    if (!container) {
      return Response.json({ skipped: 'no data' });
    }

    const fillPct = container.last_fill_pct ?? 0;
    const threshold = container.collection_threshold_pct ?? 80;

    if (fillPct < threshold) {
      return Response.json({ skipped: 'below threshold', fill_pct: fillPct });
    }

    // Fetch admin + dispatcher users
    const allUsers = await base44.asServiceRole.entities.User.list();
    const dispatchTeam = allUsers.filter(u =>
      ['admin', 'dispatcher'].includes(u.role) && u.email
    );

    const label = container.label || container.id?.slice(0, 8);
    const address = container.address || 'Unknown location';
    const stream = (container.waste_stream || 'general').replace('_', ' ');

    const emailBody = `
<h2 style="color:#dc2626">⚠ Container Capacity Alert</h2>
<p>A container has reached or exceeded its collection threshold and requires immediate pickup scheduling.</p>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;font-size:13px;margin-top:12px">
  <tr><th style="text-align:left;background:#fef2f2">Container</th><td>${label}</td></tr>
  <tr><th style="text-align:left;background:#fef2f2">Fill Level</th><td style="color:#dc2626;font-weight:bold">${fillPct}%</td></tr>
  <tr><th style="text-align:left;background:#fef2f2">Threshold</th><td>${threshold}%</td></tr>
  <tr><th style="text-align:left;background:#fef2f2">Waste Stream</th><td style="text-transform:capitalize">${stream}</td></tr>
  <tr><th style="text-align:left;background:#fef2f2">Location</th><td>${address}</td></tr>
  <tr><th style="text-align:left;background:#fef2f2">Last Reading</th><td>${container.last_reading_at || 'N/A'}</td></tr>
</table>
<p style="margin-top:16px">Please update the pickup schedule for this container.</p>
<p style="color:#888;font-size:12px">This alert was automatically generated by NLSWMS Smart Bins.</p>
    `.trim();

    for (const user of dispatchTeam) {
      await base44.asServiceRole.integrations.Core.SendEmail({
        to: user.email,
        subject: `🚨 Container ${label} at ${fillPct}% — Pickup Required`,
        body: emailBody,
      });
    }

    // Create a notification record
    await base44.asServiceRole.entities.Notification.create({
      tenant_id: container.tenant_id,
      type: 'container_capacity_alert',
      title: `Container ${label} at ${fillPct}%`,
      message: `Container "${label}" at ${address} has reached ${fillPct}% fill level (threshold: ${threshold}%). Pickup scheduling update required.`,
      severity: fillPct >= 95 ? 'critical' : 'high',
      reference_id: container.id,
      reference_type: 'Container',
      is_read: false,
    });

    return Response.json({
      success: true,
      container_id: container.id,
      fill_pct: fillPct,
      alerts_sent: dispatchTeam.length,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});