import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
import { google } from 'npm:googleapis@128.0.0';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        
        // This function is called by automation, no user auth needed
        // but we'll use service role for operations
        
        // Get the month to archive (default to last month)
        const now = new Date();
        const targetMonth = now.getMonth() === 0 ? 11 : now.getMonth() - 1;
        const targetYear = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();
        const monthYear = `${targetYear}-${String(targetMonth + 1).padStart(2, '0')}`;
        const monthLabel = new Date(targetYear, targetMonth).toLocaleString('default', { month: 'long', year: 'numeric' });

        // Fetch all successful EFRIS invoices for the month
        const invoices = await base44.asServiceRole.entities.EFRISInvoiceLog.filter({
            month_year: monthYear,
            status: 'success'
        });

        if (!invoices || invoices.length === 0) {
            return Response.json({
                message: `No EFRIS invoices found for ${monthYear}`,
                archived_count: 0
            });
        }

        // Create PDF document
        const doc = new jsPDF();
        
        // Title
        doc.setFontSize(20);
        doc.text('EFRIS Tax Compliance Report', 20, 20);
        
        doc.setFontSize(12);
        doc.text(`Period: ${monthLabel}`, 20, 30);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 38);

        // Summary statistics
        const totalGross = invoices.reduce((sum, inv) => sum + (inv.gross_amount_ugx || 0), 0);
        const totalTax = invoices.reduce((sum, inv) => sum + (inv.tax_amount_ugx || 0), 0);
        const totalNet = invoices.reduce((sum, inv) => sum + (inv.net_amount_ugx || 0), 0);

        doc.setFontSize(10);
        doc.text('Summary:', 20, 50);
        doc.text(`Total Invoices: ${invoices.length}`, 25, 57);
        doc.text(`Total Gross Revenue: UGX ${totalGross.toLocaleString()}`, 25, 64);
        doc.text(`Total Tax Collected: UGX ${totalTax.toLocaleString()}`, 25, 71);
        doc.text(`Total Net Revenue: UGX ${totalNet.toLocaleString()}`, 25, 78);

        // Invoice list table
        let y = 95;
        doc.setFontSize(11);
        doc.text('Invoice Details:', 20, y);
        y += 10;

        // Table headers
        doc.setFontSize(9);
        doc.setFont(undefined, 'bold');
        doc.text('Invoice No.', 20, y);
        doc.text('Customer', 60, y);
        doc.text('Amount (UGX)', 120, y);
        doc.text('Tax (UGX)', 160, y);
        y += 5;

        doc.setFont(undefined, 'normal');
        
        invoices.forEach((inv, index) => {
            if (y > 270) {
                doc.addPage();
                y = 20;
            }

            const rowY = y;
            doc.text(inv.invoice_number || 'N/A', 20, rowY);
            doc.text(inv.customer_name, 60, rowY, { maxWidth: 55 });
            doc.text(inv.gross_amount_ugx?.toLocaleString() || '0', 120, rowY);
            doc.text(inv.tax_amount_ugx?.toLocaleString() || '0', 160, rowY);

            y += 8;
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text(`Page ${i} of ${pageCount}`, 180, 290);
            doc.text('Generated by NLSWMS EFRIS Integration', 20, 290);
        }

        // Convert to blob
        const pdfBytes = doc.output('arraybuffer');

        // Get Google Drive connector
        const connection = await base44.asServiceRole.connectors.getConnection('googledrive');
        if (!connection) {
            throw new Error('Google Drive connector not connected. Please connect it in Settings > Integrations.');
        }

        const auth = new google.auth.OAuth2();
        auth.setCredentials({ access_token: connection.access_token });

        const drive = google.drive({ version: 'v3', auth });

        // Upload to Google Drive
        const fileName = `EFRIS_Archive_${monthYear}.pdf`;
        
        const file = await drive.files.create({
            requestBody: {
                name: fileName,
                mimeType: 'application/pdf',
                parents: ['root']
            },
            media: {
                mimeType: 'application/pdf',
                body: Buffer.from(pdfBytes)
            }
        });

        const driveUrl = `https://drive.google.com/file/d/${file.data.id}/view`;

        // Update all EFRIS logs with Drive reference
        for (const inv of invoices) {
            try {
                await base44.asServiceRole.entities.EFRISInvoiceLog.update(inv.id, {
                    google_drive_url: driveUrl
                });
            } catch (e) {
                console.error(`Failed to update EFRIS log ${inv.id}:`, e);
            }
        }

        // Create notification for admin
        const admins = await base44.asServiceRole.entities.User.filter({ role: 'admin' });
        for (const admin of (admins || [])) {
            await base44.asServiceRole.entities.Notification.create({
                tenant_id: invoices[0].tenant_id,
                user_id: admin.id,
                title: 'EFRIS Monthly Archive Created',
                message: `Successfully archived ${invoices.length} EFRIS invoices for ${monthLabel} to Google Drive.`,
                type: 'success',
                is_read: false
            });
        }

        return Response.json({
            success: true,
            message: `Successfully archived ${invoices.length} invoices to Google Drive`,
            file_id: file.data.id,
            drive_url: driveUrl,
            archived_count: invoices.length,
            total_gross_ugx: totalGross,
            total_tax_ugx: totalTax
        });

    } catch (error) {
        console.error('Archive EFRIS to Drive failed:', error);
        return Response.json({ 
            error: error.message,
            success: false
        }, { status: 500 });
    }
});