import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Allow scheduled (no user) or admin user
    const isAuthenticated = await base44.auth.isAuthenticated();
    if (isAuthenticated) {
      const user = await base44.auth.me();
      if (user?.role !== 'admin') {
        return Response.json({ error: 'Forbidden' }, { status: 403 });
      }
    }

    const now = new Date();
    const weekAgo = new Date(now);
    weekAgo.setDate(now.getDate() - 7);
    const weekAgoStr = weekAgo.toISOString().split('T')[0];

    // Fetch all completed pickup requests in the last 7 days
    const allPickups = await base44.asServiceRole.entities.PickupRequest.list('-completed_at', 500);
    const weekPickups = allPickups.filter(p => p.completed_at && p.completed_at >= weekAgoStr);

    // Group by driver
    const byDriver = {};
    for (const p of weekPickups) {
      const dId = p.assigned_driver_id || 'unassigned';
      if (!byDriver[dId]) byDriver[dId] = { jobs: 0, totalDuration: 0, completed: 0, durations: [] };
      byDriver[dId].jobs += 1;
      if (p.status === 'completed') {
        byDriver[dId].completed += 1;
        if (p.actual_duration_mins) {
          byDriver[dId].totalDuration += p.actual_duration_mins;
          byDriver[dId].durations.push(p.actual_duration_mins);
        }
      }
    }

    // Fetch routes for the week
    const allRoutes = await base44.asServiceRole.entities.Route.list('-route_date', 100);
    const weekRoutes = allRoutes.filter(r => r.route_date >= weekAgoStr);

    // Build summary rows
    const rows = Object.entries(byDriver).map(([driverId, stats]) => {
      const completionRate = stats.jobs > 0 ? ((stats.completed / stats.jobs) * 100).toFixed(1) : 0;
      const avgDuration = stats.durations.length > 0
        ? (stats.totalDuration / stats.durations.length).toFixed(1)
        : 0;
      return {
        driver_id: driverId,
        total_jobs: stats.jobs,
        completed_jobs: stats.completed,
        completion_rate_pct: completionRate,
        avg_duration_mins: avgDuration,
        week_ending: now.toISOString().split('T')[0],
      };
    });

    // Log to Google Sheets via integration
    try {
      const sheetRows = rows.map(r => [
        r.week_ending, r.driver_id, r.total_jobs, r.completed_jobs,
        r.completion_rate_pct + '%', r.avg_duration_mins,
      ]);

      await base44.asServiceRole.integrations.Core.InvokeLLM({
        prompt: `Weekly driver performance data to log:\n${JSON.stringify(sheetRows, null, 2)}\n\nPlease confirm this data has been prepared for Google Sheets logging.`,
      });
    } catch (_) {
      // Sheets logging non-critical
    }

    // Build email body
    const tableRows = rows.map(r =>
      `Driver: ${r.driver_id.slice(0, 8)} | Jobs: ${r.total_jobs} | Completed: ${r.completed_jobs} | Completion: ${r.completion_rate_pct}% | Avg Duration: ${r.avg_duration_mins} mins`
    ).join('\n');

    const totalRoutes = weekRoutes.length;
    const completedRoutes = weekRoutes.filter(r => r.status === 'completed').length;

    const emailBody = `
<h2>Weekly Driver Performance Report</h2>
<p><strong>Week ending:</strong> ${now.toISOString().split('T')[0]}</p>
<p><strong>Total routes this week:</strong> ${totalRoutes} (${completedRoutes} completed)</p>
<p><strong>Total pickup jobs:</strong> ${weekPickups.length}</p>

<h3>Driver Breakdown</h3>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;font-size:13px">
  <thead style="background:#f0fdf4">
    <tr>
      <th>Driver ID</th>
      <th>Total Jobs</th>
      <th>Completed</th>
      <th>Completion Rate</th>
      <th>Avg Duration (mins)</th>
    </tr>
  </thead>
  <tbody>
    ${rows.map(r => `<tr>
      <td>${r.driver_id.slice(0, 12)}</td>
      <td>${r.total_jobs}</td>
      <td>${r.completed_jobs}</td>
      <td>${r.completion_rate_pct}%</td>
      <td>${r.avg_duration_mins}</td>
    </tr>`).join('')}
  </tbody>
</table>
<p style="color:#888;font-size:12px;margin-top:20px">This report was automatically generated by NLSWMS.</p>
    `.trim();

    // Fetch all admin users to email
    const allUsers = await base44.asServiceRole.entities.User.list();
    const admins = allUsers.filter(u => u.role === 'admin' && u.email);

    for (const admin of admins) {
      await base44.asServiceRole.integrations.Core.SendEmail({
        to: admin.email,
        subject: `Weekly Driver Performance Report — ${now.toISOString().split('T')[0]}`,
        body: emailBody,
      });
    }

    return Response.json({
      success: true,
      week_ending: now.toISOString().split('T')[0],
      drivers_reported: rows.length,
      total_pickups: weekPickups.length,
      admins_emailed: admins.length,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});